export const ADMIN_AGENCIES = [
  {
    id: "ag-1",
    name: "Pascal Transport",
    status: "active" as const,
    cities: ["Kinshasa", "Matadi", "Boma"],
    reservations: 412,
    revenue: "6 180 $",
    commission: "10%",
  },
  {
    id: "ag-2",
    name: "Rompaga Express",
    status: "active" as const,
    cities: ["Kinshasa", "Matadi"],
    reservations: 287,
    revenue: "4 305 $",
    commission: "10%",
  },
  {
    id: "ag-3",
    name: "Limete Travel",
    status: "active" as const,
    cities: ["Kinshasa", "Kikwit", "Bandundu"],
    reservations: 198,
    revenue: "2 970 $",
    commission: "8%",
  },
  {
    id: "ag-4",
    name: "Trans Congo",
    status: "pending" as const,
    cities: ["Kinshasa", "Matadi"],
    reservations: 0,
    revenue: "0 $",
    commission: "10%",
  },
  {
    id: "ag-5",
    name: "Express Bas-Congo",
    status: "suspended" as const,
    cities: ["Matadi", "Boma"],
    reservations: 54,
    revenue: "810 $",
    commission: "10%",
  },
];

export const ADMIN_RESERVATIONS = [
  {
    id: "BC-2041",
    client: "Patrick Kabila",
    phone: "+243 81 234 5678",
    agency: "Pascal Transport",
    route: "Kinshasa → Matadi",
    date: "28 mai 2026",
    month: "2026-05",
    day: 28,
    amount: "45 $",
    commission: "4,50 $",
    paymentMethod: "Mobile Money",
    payment: "paid" as const,
    status: "confirmed" as const,
  },
  {
    id: "BC-2038",
    client: "Grace Mujinga",
    phone: "+243 82 345 6789",
    agency: "Rompaga Express",
    route: "Kinshasa → Matadi",
    date: "27 mai 2026",
    month: "2026-05",
    day: 27,
    amount: "40 $",
    commission: "4,00 $",
    paymentMethod: "En agence",
    payment: "pending" as const,
    status: "pending" as const,
  },
  {
    id: "BC-2035",
    client: "Jean Mukendi",
    phone: "+243 99 876 5432",
    agency: "Limete Travel",
    route: "Kinshasa → Kikwit",
    date: "26 mai 2026",
    month: "2026-05",
    day: 26,
    amount: "35 $",
    commission: "2,80 $",
    paymentMethod: "Carte bancaire",
    payment: "paid" as const,
    status: "dispute" as const,
  },
  {
    id: "BC-2030",
    client: "Marie Tshilombo",
    phone: "+243 97 111 2233",
    agency: "Pascal Transport",
    route: "Kinshasa → Boma",
    date: "25 mai 2026",
    month: "2026-05",
    day: 25,
    amount: "50 $",
    commission: "5,00 $",
    paymentMethod: "Mobile Money",
    payment: "paid" as const,
    status: "cancelled" as const,
  },
  {
    id: "BC-2020",
    client: "Paul Mbuyi",
    phone: "+243 97 654 3210",
    agency: "Rompaga Express",
    route: "Kinshasa → Matadi",
    date: "15 avr. 2026",
    month: "2026-04",
    day: 15,
    amount: "40 $",
    commission: "4,00 $",
    paymentMethod: "Mobile Money",
    payment: "paid" as const,
    status: "confirmed" as const,
  },
];

export type AdminReservation = (typeof ADMIN_RESERVATIONS)[number];

export type AdminAgency = (typeof ADMIN_AGENCIES)[number];

export const ADMIN_USERS = [
  {
    id: "u-1",
    name: "Patrick Kabila",
    email: "patrick.kabila@email.com",
    type: "client" as const,
    phone: "+243 81 234 5678",
    status: "active" as const,
    reservations: 4,
  },
  {
    id: "u-2",
    name: "Grace Mujinga",
    email: "grace.mujinga@email.com",
    type: "client" as const,
    phone: "+243 82 345 6789",
    status: "active" as const,
    reservations: 2,
  },
  {
    id: "u-3",
    name: "Pascal Transport",
    email: "pascal@transport.cd",
    type: "agency" as const,
    phone: "+243 99 111 2233",
    status: "active" as const,
    reservations: 412,
  },
  {
    id: "u-4",
    name: "Rompaga Express",
    email: "rompaga@transport.cd",
    type: "agency" as const,
    phone: "+243 99 444 5566",
    status: "active" as const,
    reservations: 287,
  },
  {
    id: "u-5",
    name: "Paul Mbuyi",
    email: "paul.m@email.com",
    type: "client" as const,
    phone: "+243 97 654 3210",
    status: "blocked" as const,
    reservations: 0,
  },
];

export const ADMIN_FINANCE = {
  commissions: "1 842 $",
  subscriptions: "480 $",
  payments: "18 420 $",
  monthlyGrowth: "+12%",
  history: [
    { id: "fin-1", label: "Commission Pascal Transport", amount: "+618 $", date: "26 mai 2026", type: "Commission", agency: "Pascal Transport", reference: "COM-2026-0526" },
    { id: "fin-2", label: "Abonnement Rompaga Express", amount: "+60 $", date: "25 mai 2026", type: "Abonnement", agency: "Rompaga Express", reference: "ABO-2026-0525" },
    { id: "fin-3", label: "Commission Limete Travel", amount: "+237 $", date: "24 mai 2026", type: "Commission", agency: "Limete Travel", reference: "COM-2026-0524" },
    { id: "fin-4", label: "Paiement Mobile Money", amount: "+1 240 $", date: "23 mai 2026", type: "Paiement", agency: "—", reference: "PAY-2026-0523" },
  ],
};

export const ADMIN_ANALYTICS = {
  popularCities: [
    { city: "Kinshasa", trips: 842 },
    { city: "Matadi", trips: 612 },
    { city: "Boma", trips: 284 },
    { city: "Kikwit", trips: 198 },
  ],
  topAgencies: [
    { name: "Pascal Transport", tickets: 412, growth: "+18%" },
    { name: "Rompaga Express", tickets: 287, growth: "+9%" },
    { name: "Limete Travel", tickets: 198, growth: "+14%" },
  ],
  ticketsSold: "1 248",
  monthlyTicketSales: {
    all: [
      { month: "Jan", tickets: 820 },
      { month: "Fév", tickets: 910 },
      { month: "Mar", tickets: 980 },
      { month: "Avr", tickets: 1050 },
      { month: "Mai", tickets: 1248 },
    ],
    byAgency: {
      "Pascal Transport": [
        { month: "Jan", tickets: 280 },
        { month: "Fév", tickets: 310 },
        { month: "Mar", tickets: 340 },
        { month: "Avr", tickets: 360 },
        { month: "Mai", tickets: 412 },
      ],
      "Rompaga Express": [
        { month: "Jan", tickets: 190 },
        { month: "Fév", tickets: 210 },
        { month: "Mar", tickets: 230 },
        { month: "Avr", tickets: 260 },
        { month: "Mai", tickets: 287 },
      ],
      "Limete Travel": [
        { month: "Jan", tickets: 140 },
        { month: "Fév", tickets: 155 },
        { month: "Mar", tickets: 170 },
        { month: "Avr", tickets: 185 },
        { month: "Mai", tickets: 198 },
      ],
    },
  },
  monthlyGrowth: [
    { month: "Jan", value: 820 },
    { month: "Fév", value: 910 },
    { month: "Mar", value: 980 },
    { month: "Avr", value: 1050 },
    { month: "Mai", value: 1248 },
  ],
};

export const ADMIN_RECENT_ACTIVITY = [
  { label: "Nouvelle réservation Kinshasa → Matadi", time: "Il y a 12 min" },
  { label: "Agence Pascal Transport validée", time: "Il y a 1 h" },
  { label: "Paiement confirmé — 45$", time: "Il y a 2 h" },
  { label: "Litige résolu #BC-1042", time: "Il y a 3 h" },
  { label: "Nouvelle agence en attente — Trans Congo", time: "Il y a 5 h" },
];
