export const AGENCY_TRIPS = [
  {
    id: "t-1",
    agencyId: "agency-1",
    from: "Kinshasa",
    to: "Matadi",
    time: "06h00",
    price: "45 $",
    seats: 40,
    remaining: 12,
    status: "active" as const,
  },
  {
    id: "t-2",
    agencyId: "agency-1",
    from: "Kinshasa",
    to: "Matadi",
    time: "14h00",
    price: "45 $",
    seats: 40,
    remaining: 8,
    status: "active" as const,
  },
  {
    id: "t-3",
    agencyId: "agency-1",
    from: "Kinshasa",
    to: "Boma",
    time: "07h30",
    price: "50 $",
    seats: 35,
    remaining: 15,
    status: "active" as const,
  },
  {
    id: "t-4",
    agencyId: "agency-2",
    from: "Kinshasa",
    to: "Matadi",
    time: "08h00",
    price: "40 $",
    seats: 45,
    remaining: 20,
    status: "active" as const,
  },
  {
    id: "t-5",
    agencyId: "agency-2",
    from: "Kinshasa",
    to: "Matadi",
    time: "16h00",
    price: "40 $",
    seats: 45,
    remaining: 18,
    status: "active" as const,
  },
];

export const AGENCY_RESERVATIONS = [
  {
    id: "r-1",
    agencyId: "agency-1",
    client: "Patrick Kabila",
    phone: "+243 81 234 5678",
    route: "Kinshasa → Matadi",
    date: "28 mai 2026",
    dateIso: "2026-05-28",
    time: "06h00",
    seat: "A12",
    payment: "paid" as const,
    status: "confirmed" as const,
    present: false,
  },
  {
    id: "r-2",
    agencyId: "agency-1",
    client: "Grace Mujinga",
    phone: "+243 82 345 6789",
    route: "Kinshasa → Matadi",
    date: "30 mai 2026",
    dateIso: "2026-05-30",
    time: "14h00",
    seat: "B04",
    payment: "pending" as const,
    status: "pending" as const,
    present: false,
  },
  {
    id: "r-3",
    agencyId: "agency-1",
    client: "Jean Mukendi",
    phone: "+243 99 876 5432",
    route: "Kinshasa → Boma",
    date: "27 mai 2026",
    dateIso: "2026-05-27",
    time: "07h30",
    seat: "C08",
    payment: "paid" as const,
    status: "confirmed" as const,
    present: true,
  },
  {
    id: "r-4",
    agencyId: "agency-2",
    client: "Marie Tshilombo",
    phone: "+243 97 111 2233",
    route: "Kinshasa → Matadi",
    date: "29 mai 2026",
    dateIso: "2026-05-29",
    time: "08h00",
    seat: "D02",
    payment: "paid" as const,
    status: "confirmed" as const,
    present: false,
  },
];

export const AGENCY_TRAVELERS = AGENCY_RESERVATIONS.map((r) => ({
  id: r.id,
  agencyId: r.agencyId,
  name: r.client,
  phone: r.phone,
  ticket: `BC-${r.id.split("-")[1]}204`,
  qr: `BUSCONNECT:${r.agencyId}:${r.id}:${r.client.replaceAll(" ", "_")}`,
  travelDate: r.date,
  travelDateIso: r.dateIso,
  route: r.route,
}));

export const AGENCY_PAYMENTS = [
  {
    id: "p-1",
    agencyId: "agency-1",
    label: "Réservation BC-1204 — Patrick Kabila",
    type: "online" as const,
    amount: "45 $",
    commission: "4,50 $",
    date: "27 mai 2026",
  },
  {
    id: "p-2",
    agencyId: "agency-1",
    label: "Réservation BC-1205 — Grace Mujinga",
    type: "physical" as const,
    amount: "45 $",
    commission: "4,50 $",
    date: "27 mai 2026",
  },
  {
    id: "p-3",
    agencyId: "agency-2",
    label: "Réservation BC-2204 — Marie Tshilombo",
    type: "online" as const,
    amount: "40 $",
    commission: "4,00 $",
    date: "26 mai 2026",
  },
];

export const AGENCY_REVIEWS = [
  {
    id: "rev-1",
    agencyId: "agency-1",
    client: "Patrick Kabila",
    rating: 5,
    comment: "Voyage confortable, bus à l'heure. Je recommande.",
    date: "20 mai 2026",
  },
  {
    id: "rev-2",
    agencyId: "agency-1",
    client: "Grace Mujinga",
    rating: 4,
    comment: "Bon service, accueil agréable à l'agence.",
    date: "15 mai 2026",
  },
  {
    id: "rev-3",
    agencyId: "agency-2",
    client: "Jean Mukendi",
    rating: 4,
    comment: "Prix correct et trajet ponctuel.",
    date: "10 mai 2026",
  },
];

export function filterByAgency<T extends { agencyId: string }>(items: T[], agencyId: string) {
  return items.filter((item) => item.agencyId === agencyId);
}
